### ISSUE TITLE
local time

### ISSUE THREAD

**Issue by julmot** [Justineo/github-hovercard#28]
When working with people around the world it would be very helpful to know the local time of them. This can be determined by the location they have (possibly) provided.

Steps:
1. Detect if they have provided a location
2. Detect the timezone by the location (maybe with a third party service)
3. Display the time with the timezone in user hovercards

**Comment by Justineo** [comment]
It would be a helpful feature in some occations but I think the extension will probably continue to be an easy access to the information GitHub *already* provided. I think this may be a bit of overkill but will still keep this issue open for a while, to see if there are others who want this feature.

Thanks for the suggestion! :smile:

**Comment by julmot** [comment]
Honestly, I don't think someone will reply here. I as a user only visited the issues after I stumbled on one. 

However, why do you want to limit the information to just those that are available on GitHub itself? I don't see a disadvantage of implementing this.

**Comment by Justineo** [comment]
Because it looks like this feature probably need to depend on a third party API, which will introduce quite many further problems to solve.

The step 2 you mention actually is a little complicated.

* Fetching data may become slower.
* Not all APIs support cross domain browser requests (via CORS).
* Location name to altitude/latitude may need another request.
* Is the API able to deal with multi-language location names?
* It probably have request limitations too. We have to to enable users to bind access tokens for this API.
* ...

**Comment by julmot** [comment]
![here-we-go](https://cloud.githubusercontent.com/assets/8310677/15645849/0bdeb024-265b-11e6-912a-c15e6439ad6f.png)

**Comment by Justineo** [comment]
Yes, it's great if GitHub support this. Calculating this using location info from an extension may be an overkill. Let users set their timezones seems much easier.

**Comment by Justineo** [comment]
(But GitHub usually moves slowly for feature requests...)

**Comment by julmot** [comment]
Reply from @staceb
![stacey](https://cloud.githubusercontent.com/assets/8310677/15649127/69bfca5c-266f-11e6-820c-43c9de1814a8.png)
I'll let you know when there is any update on this.

**Comment by Justineo** [comment]
Let's wait to see if GitHub will support time zone settings.
