### ISSUE TITLE
Plugin is very slow on some pages

### ISSUE THREAD

**Issue by koppor** [Justineo/github-hovercard#32]
I get the script termination warnings at some pages when this plugin is activated. It complains at a line in jquery.js.

Example site where I have issues: https://github.com/JabRef/jabref/pull/1479

Can the plugin be disabled on certain pages?

**Comment by Justineo** [comment]
I can't reproduce your problem right now. The example URL didn't seem to be any different from other pages on my side. What's your OS/browser?

**Comment by koppor** [comment]
Firefox 47.0.1 on Microsoft Windows Version 10.0.10586 (latest Windows 10 Pro)

**Comment by Justineo** [comment]
Thanks, I'll look into this soon.

**Comment by Justineo** [comment]
The latest version has fixed this issue. The Firefox Add-on is still under review and will be published soon. @koppor

GitHub Hovercard is using `MutationObserver` to track down content change on GitHub and GitHub periodically updates the timestamps in the page (which may contain many timestamps if the issue has a lot of comments) so that the content extraction performed by GitHub Hovercard was kept running for a long time. Just fixed this by filtering mutation events triggered by those timestamps.
