### ISSUE TITLE
jQuery Hangs on Github Feed More

### ISSUE THREAD

**Issue by louy2** [Justineo/github-hovercard#35]
I finally found this reproducible case of hanging jQuery of hovercard.

1. Sign in GitHub
2. Scroll to bottom of feed
3. Click "More"

**Comment by Justineo** [comment]
Thanks for reporting. I looked into this and found it's actually the same problem as #32. Timestamps on the feed will be turned into relative time after page load. This triggers GitHub Hovercard to re-scan the page content to find if there is new extractable content.

The problem will be fixed in v0.7.2.
