### ISSUE TITLE
Enhance Repository Search-Results Hovercards

### ISSUE THREAD

**Issue by sahal2080** [Justineo/github-hovercard#40]
On repository search-results page, it'd be far more productive if the hovercard parses and shows the readme of the project (something similar to what it does with on the Issues page). Right now the only extra bit of information it's adding is the number of issues the project has.

Thank you for having a Firefox version btw 👍

**Comment by Justineo** [comment]
@sahal2080 

That will lead to 2 more AJAX request to the GitHub API (one for getting readme content and the other one for converting `.md` content into HTML). Readme files can be very large and this feature may extremely slow down displaying repo cards.

Yet this is also useful so I will try to implement this later. (Maybe we'd better add an option for it in case others don't like this.)

**Comment by sahal2080** [comment]
I'm all for having options! Performance doesn't have to suffer much if we think about it only as a _preview_:
- Cancel the second API call and instead use [showdown](https://github.com/showdownjs/showdown) on the [client side](https://github.com/showdownjs/showdown/wiki/extensions). It does original markdown which suffices for preview purposes
- Have a limit on the number of characters showdown would process (for cases where a repo author put their life story in the readme file, etc.)

**Comment by Justineo** [comment]
@sahal2080 

Actually I did render Markdown content on the client side in earlier versions of this extension. After I tried Marked and Remarkable, I found it hard to get the same result as GitHub itself because they might not take care of GitHub's extensions for Markdown such as emojis, short links for issues/repos and so on. What's more, I have to deal with XSS filtering on the client side too. So I decided to use GitHub's own Markdown rendering service to ease the pain.

**Comment by Justineo** [comment]
@sahal2080 

Actually I did render Markdown content on the client side in earlier versions of this extension. After I tried Marked and Remarkable, I found it hard to get the same result as GitHub itself because they might not take care of GitHub's extensions for Markdown such as emojis, short links for issues/repos and so on. What's more, I have to deal with XSS filtering on the client side too. So I decided to use GitHub's own Markdown rendering service to ease the pain.

**Comment by Justineo** [comment]
The feature is implemented as discussed earlier (with an option to turn off) and will be shipped in the next version (`0.9.0`). And I found that rendered readme files are directly available from GitHub API (no need for the third request for Markdown rendering).
