### ISSUE TITLE
Is it possible to show whether the particular user is following me?

### ISSUE THREAD

**Issue by djyde** [Justineo/github-hovercard#9]

**Comment by Justineo** [comment]
Yes. And also follow/unfollow/star/unstar features may be shipped in next major update (only works for users who have already provided access key).

**Comment by Justineo** [comment]
I implemented this but decided to revert back because the feature requires three AJAX requests at one time to show user information. This might be bothering for those who haven't bound their access tokens and I don't quite like too much information inside a user hovercard and it's not easy to make it neat and clean. So I'll not shipping this feature in the next releases.
